### ISSUE TITLE
[Feature Request] gif to webp

### ISSUE THREAD

**Issue by nenge123** [dlemstra/magick-wasm#101]
### Is your feature request related to a problem? Please describe.

15MB to big.

### Describe the solution you'd like

Single function, gif converted to webp
> 单一功能,gif转为为webp

### Additional context

Simple format conversion, canvas can be easily implemented, but animations can only be converted to single frames
> 单纯的格式转换,canvas可以轻易实现.但是动画只能转换单帧.

**Comment by nenge123** [comment]
Can we combine the advantages of both?


### mk33mk333/wasm-im
> that one have 14-18S, original size 33% encode. wasm file have 4MB.  
> demo https://renzhezhilu.github.io/webp2jpg-online-demo/src/gifToWebp-Stable/gifToWebp-Stable.html

### xiaozhuai/webp_encoder
> that one have 1.5-5S, original size 80%-120% encode., wasmfile 500KB.  
demo https://xiaozhuai.github.io/webp_encoder/

**Comment by dlemstra** [comment]
I really don't understand what you are asking me? You are saying multiple things and I don't know what you think you are missing?

**Comment by nenge123** [comment]
Thank you, I have found a solution
.
https://github.com/xiaozhuai/webp_encoder/tree/master/dist
