### ISSUE TITLE
Nef format to jpg color incorrect

### ISSUE THREAD

**Issue by sfyang2** [dlemstra/magick-wasm#110]
### magick-wasm version

0.0.23

### Description

Color error when reading. nef file and converting to jpg format

.nef source file : https://github.com/sfyang2/nefFile/

### Steps to Reproduce

```
function toJpg(inout: string, out: string) {
    return new Promise<void>(async (resolve, reject) => {
        try {
            const file = await fs.readFile(input)
            ImageMagick.read(file, MagickFormat.Nef, async (image) => {
                await image.write(MagickFormat.Png, async (data) => {
                    fs.writeFile(out, Buffer.from(data)).then(resolve).catch(reject);
                })
            })

        } catch (error) {
            console.log('ImageMagick.read error');
            reject(error)
        }
    })
}
```

### Images

![image](https://github.com/dlemstra/magick-wasm/assets/46621212/de86fb91-02eb-403a-a867-39d9d734a2f6)

**Comment by dlemstra** [comment]
Have you tried using the `DngReadDefines`? One of those options might resolve your issue.

**Comment by sfyang2** [comment]
> Have you tried using the `DngReadDefines`? One of those options might resolve your issue.

Thank you for your reply. Where can I see the relevant documents for DngReadDefinitions

**Comment by dlemstra** [comment]
You can find some documentation here: https://imagemagick.org/script/defines.php if you scroll down to the part that mentions `dng:`.
