### ISSUE TITLE
Add jsdoc comments to existing code

### ISSUE THREAD

**Issue by with-heart** [dlemstra/magick-wasm#116]
### Is your feature request related to a problem? Please describe.

The API of the library is quite broad and it can be difficult for new users to understand its many parts.

### Describe the solution you'd like

Adding jsdoc comments to the codebase provides immediate context to our users of the library. The comments serve as documentation about various parts of the library *at the point of use*, increasing ease-of-use and reducing the amount of searching users must do in order to gain understanding.

### Additional context

This library's API and structure are closely inspired by [@dlemstra/Magick.Net](https://github.com/dlemstra/Magick.NET) which already contains a large number of documentation comments. We should try to reuse these as much as possible.

**Comment by dlemstra** [comment]
Thanks for raising this issue. I have added documentation to all the existing code and this will become available in the next release.
