### ISSUE TITLE
Not working in web worker

### ISSUE THREAD

**Issue by julenwang** [dlemstra/magick-wasm#127]
### magick-wasm version

0.0.26

### Description

Not working in web worker context

I cannot find this code in repo,  I guess it generated by compiler

Sorry, My English is bad

### Steps to Reproduce

use @imagemagick/magick-wasm in web worker

### Images

<img width="743" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/42799169/f3fbb2a1-a26a-4d5b-a680-9a87c35eebc0">
<img width="840" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/42799169/8067a13b-44fc-4531-bebe-9feb9a5be62d">
<img width="1070" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/42799169/c38d65ec-f093-4e21-95c3-2991df2ab2a7">

**Comment by julenwang** [comment]
I fixed it use patch-package, It is working well

```
diff --git a/node_modules/@imagemagick/magick-wasm/dist/index.mjs b/node_modules/@imagemagick/magick-wasm/dist/index.mjs
index 2a43ef4..2ef32fb 100644
--- a/node_modules/@imagemagick/magick-wasm/dist/index.mjs
+++ b/node_modules/@imagemagick/magick-wasm/dist/index.mjs
@@ -95,9 +95,19 @@ class Hi {
    */
   message;
 }
+
 var Fi = (() => {
   var t = typeof document < "u" && document.currentScript ? document.currentScript.src : void 0;
   return function(a = {}) {
+
+    // hack in worker
+    if(typeof window === "undefined"){
+      var window = {
+        crypto,
+        prompt: console.log
+      }
+    }
+
     var e = a, l, m;
     e.ready = new Promise((n, r) => {
       l = n, m = r;

```

**Comment by nathan-nusign** [comment]
I can confirm that this patch fixes the issue. It would be great to get this merged soon!

**Comment by dlemstra** [comment]
@Peeterush created a PR to resolve this. But I also wonder if we could add an extra check to test if the code can be executed in a webworker and maybe also inside a web browser?
