### ISSUE TITLE
Not able to load .heic images

### ISSUE THREAD

**Issue by wayjake** [dlemstra/magick-wasm#138]
### magick-wasm version

0.0.3

### Description

I intend to convert HEIC images from iphones to be the more standard JPG upon uploading to my website. Currently I am able to load a JPG image, however HEIC give a run time error which appears to come deep within the wasm execution. 

### Steps to Reproduce

The easiest way to demonstrate this bug is to attempt to load a HEIC image into the [magic-image demo](https://dlemstra.github.io/magick-wasm-docs/classes/magick-image) on the official Magick-Wasm docs site. Here is a sample file that is broken on my end: http://nice.4d2.io/IMG_3736.HEIC

### Images

<img width="722" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/3623016/fcee6311-64a2-45f3-b0a5-0f5f033439ce">
<img width="1248" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/3623016/c10f40db-5b55-4239-9f9e-42d451a90ab4">

**Comment by dlemstra** [comment]
Thanks for reporting this. It turns out that I forgot to add a build open when I had to make changes to the build of the `libheif` library that is used to read `.heic` files. This issue will be resolved in the next release that will be published sometime next week.

**Comment by wayjake** [comment]
woot woot! all good on my end!
