### ISSUE TITLE
Can't read attribute `exif:UserComment`

### ISSUE THREAD

**Issue by biw** [dlemstra/magick-wasm#145]
### magick-wasm version

0.0.28

### Description

Hello, thanks for writing a great library. I've been testing reading metadata written by [`exiftool-vendored`](https://www.npmjs.com/package/exiftool-vendored) and I have an issue when reading `exif:UserComment`. It returns the string `ASCII` rather than the set value.

I also tried to install the package myself and debug but got the following issue when running `npm install`:

```
 401 Unauthorized - GET https://npm.pkg.github.com/download/@dlemstra/magick-native/0.202401.211644/e0461179a3b8940cc63cdde6fac732304f125bc2 - unauthenticated: User cannot be authenticated with the token provided.
```

### Steps to Reproduce

To reproduce:
```ts
const outputPath = '~/Desktop/img.png'
// write a comment using exiftool
  exifTool.write(outputPath, {
        UserComment: JSON.stringify({
          x: 'info'
          // more JSON
          }),
      })
```
then
```ts
ImageMagick.read(new Uint8Array(text), async (image) => {
  console.log(image.getAttribute('exif:UserComment')) // prints 'ASCII'
})
```

### Images

![Fara12dday](https://github.com/dlemstra/magick-wasm/assets/6139501/06bb9f83-5e97-4db7-be3b-4cc1897d12f4)

**Comment by dlemstra** [comment]
Can you share a file that can be used to reproduce this issue. This project uses a native library that you will need to debug instead. If you would want to debug this I would advise you to debug the ImageMagick command line tools instead.

p.s. This project gets the native library from GitHub packages and that requires a token.

**Comment by biw** [comment]
> This project uses a native library that you will need to debug instead. If you would want to debug this I would advise you to debug the ImageMagick command line tools instead.
> 
> p.s. This project gets the native library from GitHub packages and that requires a token.

Sorry for my late response, I missed the notification! It is indeed a problem with `ImageMagick` itself and I can recreate it with the command line too

> Can you share a file that can be used to reproduce this issue. 

One is included in the original post under images (the command line image)

I'm going to close this issue as it's not an issue with the wasm package 🙂
