### ISSUE TITLE
Distorting creates black dotted border

### ISSUE THREAD

**Issue by gemini133** [dlemstra/magick-wasm#146]
### magick-wasm version

0.0.28

### Description

magick-wasm information:

ImageMagick 7.1.1-27 Q8 x86_64 0225ac41a:20240121 https://imagemagick.org
freetype heic jng jp2 jpeg jxl lcms lqr openexr png raw tiff webp xml zlib

here is the code and the test image

![image](https://github.com/dlemstra/magick-wasm/assets/18028552/4f734a2b-aae3-451e-8dfe-887ff11262a0)

```
import { initializeImageMagick, ImageMagick, DistortMethod, Gravity, MagickColors } from './index';
(async () => {
  await initializeImageMagick()
  const image = await fetch('image.png')
  const imagebody = await image.arrayBuffer()
  ImageMagick.read(new Uint8Array(imagebody), async (image) => {
    image.extent(872, 135, Gravity.Center)
    image.distort(DistortMethod.BarrelInverse, [0,0,0,1,0,-0.0485,0,2])
    image.draw()
    image.writeToCanvas(document.querySelector('#canvas'))
  });
})()


```

here is the image written to the canvas

<img width="1113" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/18028552/38734a82-6064-443f-852c-d3c5a3b31b8a">

----

I tried with  `convert image.png -gravity center -extent 872x135 -distort BarrelInverse "0,0,0,1,0,-0.0485,0,2" a.png` and it didn't create black dotted border.

<img width="970" alt="image" src="https://github.com/dlemstra/magick-wasm/assets/18028552/181b1168-fb09-4022-9303-2b9869b4466e">

```
convert --version
Version: ImageMagick 7.1.1-23 Q16-HDRI aarch64 21803 https://imagemagick.org
```

### Steps to Reproduce

please check the description

**Comment by gemini133** [comment]
Not sure if this issue belongs to magick-wasm. Pleas let me know if you need more info.  Thanks in advance.

**Comment by dlemstra** [comment]
Can you zip your input file and add it again? It looks like GitHub is doing something with it. But that might also be the reason why you see artifacts.

**Comment by gemini133** [comment]
thanks for looking up.

the wasm file inside is from https://github.com/dlemstra/magick-wasm/actions/runs/7806126825 artifacts.

https://drive.google.com/file/d/1akc-94FA7WKSjHPgMW6GUMQ5V-bovdWx/view?usp=sharing

please install vite and `npm run dev`, right click the canvas and save as image.

**Comment by dlemstra** [comment]
What happens when you move the unnecessary `image.draw()` statement?

**Comment by gemini133** [comment]
Didn't know the `draw()` is optional.  Ijust now removed it,  still the same, dotted border.
no worry,  the code in google drive link is workable, if you have time, you can play it around.

**Comment by dlemstra** [comment]
I can reproduce your issue and it seems to be a 32-bit issue. I am unable to reproduce this with my 64-bit ImageMagick build. So this will require some more debugging to figure out why this is happning.

**Comment by gemini133** [comment]
hm, it's a subtle bug. could be a problem of imagemagick.
could you let me know how to build the 64bit version? any build file I should change ?

**Comment by dlemstra** [comment]
It is an issue inside ImageMagick that needs to be addressed there.

**Comment by dlemstra** [comment]
This issue will be resolved in the next release.

**Comment by gemini133** [comment]
thanks! tried the latest ones (Magick.Native and Imagemagick), it's gone
