### ISSUE TITLE
Some images when converting (PNG->JPG for example) are corrupted

### ISSUE THREAD

**Issue by lancejpollard** [dlemstra/magick-wasm#149]
### magick-wasm version

0.0.28

### Description

I don't know if I'm doing something wrong, but you've seen my main code. It created this JPG:

![equation](https://github.com/dlemstra/magick-wasm/assets/28718/bb3865f0-5e3e-4e30-b71b-fc8a50fd676d)

From this PNG:

![equation](https://github.com/dlemstra/magick-wasm/assets/28718/4337c139-a2b6-449e-8194-652239cbc175)

Also I'm getting a lot of files which just won't open either.

### Steps to Reproduce

Just run the hello world example on these files.

**Comment by dlemstra** [comment]
Please don't create an issue without information to reproduce the issue.
