### ISSUE TITLE
Fails with Images with more than 5MB with Dedicated Worker

### ISSUE THREAD

**Issue by abduljabbar021** [dlemstra/magick-wasm#160]
### magick-wasm version

0.0.28

### Description

When trying to adjust the quality of any image with more than 4-5mb, it fails.

Output of Successful Image processing (below 4-5mb size)

![Screenshot from 2024-04-06 12-22-17](https://github.com/dlemstra/magick-wasm/assets/98426089/d1563fa5-d390-4685-bfdd-955cc8bb27fb)

Output of Failed Image processing (more than 4-5mb size)

![Screenshot from 2024-04-06 12-27-39](https://github.com/dlemstra/magick-wasm/assets/98426089/f3010566-6131-40bb-97c7-f164cae19b1a)

here is very basic code from Dedicated Worker

    wk.onmessage = async function(event){
        const response = await fetch(event.data.source);
        const buffer = await response.arrayBuffer();
        const data = new Uint8Array(buffer);
        entireMagickLibrary.ImageMagick.read(data, image => {
            image.quality = 5;
            image.write(entireMagickLibrary.MagickFormat.Jpeg, data => {
                wk.postMessage(data);
            });
        });
    };
    wk.postMessage({ init: true });

Rest of the code is similar to this [https://github.com/dlemstra/magick-wasm/discussions/112](url)

I tried setting image quality between 5-80 but it always fail if image size is larger than 4-5mb

### Steps to Reproduce

1) Following this disucssion to create dedicated worker, browser based only https://github.com/dlemstra/magick-wasm/discussions/112

2) Adjust Image Quality and it fails where image size is larger than 4-5mb

**Comment by dlemstra** [comment]
The size of the input image is not relevant. I suspect this happens when the width/height of the image is large. And because of that you seem to be running out of memory at some point. Because wasm is 32-bit you will run out of memory much fast than on a 64-bit platform. In the future there will probably be support for 64-bit web assembly but until then you will have a memory limit.

**Comment by dlemstra** [comment]
There are no options? There is a memory limit and you are running into that limit.

**Comment by julenwang** [comment]
Did you try to use IndexDB storage processed images?
I have processed more than 200 images. That is OK.
This is my [repo](https://github.com/julenwang/wx-moments-helper/blob/main/src/views/Main/ImageProcessor/ImageProcessFuncs.ts#L74).
