### ISSUE TITLE
Getting strange Error when trying convert GIF to APNG

### ISSUE THREAD

**Issue by salivity** [dlemstra/magick-wasm#162]
### magick-wasm version

^0.0.26

### Description

Unable to do a direct conversion from GIF to APNG which should be efficient using this superior format.

### Steps to Reproduce

                ```
                let quality = typeof options.quality !== "undefined" ? options.quality : 75;
    
                ImageMagick.read(new Uint8Array(array_buffer), async (img) => {

                    img.quality = quality; 
                    img.format = MagickFormat.Apng;

                    img.settings.setDefine(MagickFormat.Apng, "delay", 100);
                    img.settings.setDefine(MagickFormat.Apng, "loop", 0);

                    if(typeof width !== "undefined" && typeof height !== "undefined"){
                        img.resize(width, height);
                    }

                    img.write((data) => {
                       self.postMessage({type: "complete", array: data, extension: "apng", mimetype: "image/apng"})
                    }, )

                }).then(() => {

                }).catch((error) => {
                    self.postMessage({type: "error", message: error.message})
                })
```

Returns the following Error from write();

FailedToExecuteCommand `'ffmpeg' -nostdin -loglevel error -i '/tmp/magick-HdhKcrR_dR72Zw4PskXq_uKw5qNLfKFg%d.webp' -plays 0 '/tmp/magick-qwJqhHIO9BHhnZIPmnHwGG9wYnojAjFC.APNG'' (-1) @ error/delegate.c/ExternalDelegateCommand/522

**Comment by dlemstra** [comment]
You are getting this error message because the output format is `apng` and that requires `ffmpeg` that is not available in the WASM implementation.

**Comment by li-yang-8** [comment]
> 您收到此错误消息是因为输出格式是，`apng`并且要求`ffmpeg`在 WASM 实现中不可用。

怎么才能支持webp转apng呢？
` imageReaded.write(MagickFormat.APng, (data) => {
            try {
              const blob = new Blob([data], { type: 'image/png'});
              res(blob);
            } catch (error) {
              rej(error);
            }
          });`
