### ISSUE TITLE
unable to clone and npm install

### ISSUE THREAD

**Issue by iambumblehead** [dlemstra/magick-wasm#164]
### magick-wasm version

main

### Description

magick-wasm cannot be cloned and installed

### Steps to Reproduce

```bash
$ npm install
npm error code E401
npm error 401 Unauthorized - GET https://npm.pkg.github.com/download/@dlemstra/magick-native/0.202405.171632/3db3ec2a9bbb94aeafb76db16a58fa52ffa05a25 - authentication token not provided
npm error A complete log of this run can be found in: /home/bumble/.npm/_logs/2024-06-16T04_56_17_800Z-debug-0.log
```

**Comment by iambumblehead** [comment]
After experimenting with this file https://github.com/dlemstra/magick-wasm/blob/main/demo/demo.ts, would like permission to make a few changes updating the file so it can be used directly with less modification afterward. 

 1. **Change demo.ts to demo.js.** If "js" is used, it will be easier to link moduleId "@imagemagick/magick-wasm" with a local path to package "demo/../" so magick-wasm's demo folder will be able import magick-wasm from itself. 'Could experiment more to try achieving this with ts but am less certain about the result.
 2. **Remove reference to @dlemstra/magick-native/magick.wasm** and instead use @imagemagick/magick-wasm/magick.wasm this will make the file easier for other people to copy-paste and use as-is
 3. **Remove the promise 'catch' call at the end.** catch only calls console.log so the error's natural course will be fine

**Comment by dlemstra** [comment]
I have added a file called `CONTRIBUTING.md` to make it clear what needs to be done to install the dependencies of this project.

1. I would prefer to keep this as a typescript file.
2. There is a comment above this line that explains what you need to do when using this in your own project.
3. That's a good idea I have removed that part.

**Comment by iambumblehead** [comment]
fair enough, closing this issue
