### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Miki-AG** [dlemstra/magick-wasm#171]
### magick-wasm version

0.0.30

### Description

npm install
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@dlemstra/magick-native/0.202407.160648/8f584ddddf4da949e3402df0bd8cc24f9255f06c - authentication token not provided

npm ERR! A complete log of this run can be found in: /Users/miargar/.npm/_logs/2024-08-14T13_05_54_083Z-debug-0.log

### Steps to Reproduce

Follow installation steps:
- Clone rep
- npm install

**Comment by dlemstra** [comment]
You can find more information here: https://github.com/dlemstra/magick-wasm/blob/main/CONTRIBUTING.md.
