### ISSUE TITLE
Corrupted files produced when writing certain images as WebP

### ISSUE THREAD

**Issue by JeongJuhyeon** [dlemstra/magick-wasm#185]
### magick-wasm version

0.0.31

### Description

For certain images, `image.write(MagickFormat.WebP, ..)` produces an unreadable file with no header that corresponds to any image format. Swapping `MagickFormat.WebP` for e.g. `MagickFormat.Png` while keeping everything else the same produces a valid image given the same input data. In our case, this only happens for a small percentage of input images, but is consistent.

### Images

Here are a problematic original image + the images produced by magick-wasm when using respectively `MagickFormat.WebP` (corrupted) and `MagickFormat.Png` (successful): [Archive.zip](https://github.com/user-attachments/files/17502342/Archive.zip)

**Comment by dlemstra** [comment]
How are you saving the file?

**Comment by JeongJuhyeon** [comment]
> How are you saving the file?

In our usecase we're using the results in-memory without saving them to disk. We've only saved them now to help debug the issue here. We've confirmed that the corruption before saving the file by printing to console the first view bytes from the buffer/UInt8Array in memory that results from `image.write`. The printed bytes are the same as those of the image in the zip file as seen in a hex editor `28 e3 67 00`.

**Comment by JeongJuhyeon** [comment]
Confirmed the bug is likely not in ImageMagick. The buffer content gets changed upon returning it from a function, which is quite baffling but unrelated.

**Comment by dlemstra** [comment]
I have updated the documentation of that method to make it more clear to explain why that happens:

```js
/**
 * Writes the image to a byte array.This array points to native memory and will be give back to the native
 * memory manager after the excution of the function. A copy of the data should be made if it needs to be
 * used after the function has completed.
 */
```
