### ISSUE TITLE
Can't build in Vite

### ISSUE THREAD

**Issue by Peeterush** [dlemstra/magick-wasm#41]
### magick-wasm version

Any

### Description

When trying to build with Vite, it gives the following warning, but not always on the same file:
`'ws' is imported by ws?commonjs-external, but could not be resolved – treating it as an external dependency`
It decides to alias `ws` to `require$$2`, which doesn't exist, breaking the build.

I tried installing `ws`, which stops Vite from complaining. But the build still doesn't work, saying that `Buffer` does not exist, suggesting it tries to run in a node environment.

From what I can find, the problematic code resides in `@imagemagick/magick-wasm/wasm/magick.js`.

### Steps to Reproduce

Set up a minimal project (use single `--` for npm 6 and under):
```
npm init vite vite-build-test -- --template vanilla
cd vite-build-test
npm i @imagemagick/magick-wasm
```
Overwrite `main.js` to contain only the following:
```
import { initializeImageMagick } from "@imagemagick/magick-wasm";
```
Then try `npm run build`

Optionally serve the freshly created build: `npm run preview`

**Comment by dlemstra** [comment]
I have experience with Vite so I don't know what is causing this. Someone else ran into the same issue and they created this: https://github.com/Armster15/imagemagick-wasm-builds. It says they don't know why this breaks but maybe you can find out by how they solved it?

**Comment by Peeterush** [comment]
By now I've spent many hours trying to figure this out and I too can't find the underlying problem. It seems that `@dlemstra/magick-native` needs a build step that Vite (Rollup under the hood) can't provide, also not with polyfills (that is what the linked repository does with Webpack).

**Comment by Peeterush** [comment]
I'm trying to get things working with Webpack instead, and looked at [@dlemstra/magick-wasm-docs](https://github.com/dlemstra/magick-wasm-docs) to see your configuration. But just running `git clone` and `npm i` doesn't result in a working application, neither with `serve` nor with `build`. Webpack doesn't give any errors, but in both cases stuff just doesn't work in the browser. The only pointer so far is a whole lot of complaining from npm while installing about deprecated packages and mismatched versions, and the lock file being from an old version of npm. Do you have some custom configuration for node or npm that makes this work for you?

**Comment by Peeterush** [comment]
I've been experimenting with the repo you linked, stripping it down to the bare minimum to get a functional build. It seems a lot of their configuration is for additional things, not just being able to build.

The main thing that seems to make it work is making sure that Webpack knows what to do with a couple of nodejs modules. The linked package resolves some using browser polyfills, and disables resolution for others. I found that disabling only `ws`, `fs`, `child_process`, `crypto` and `path` already results in something that Vite plays well with, without specifying resolution for anything else.

Given this knowledge I've tried achieving the same thing with Vite, but no such luck. But if `@imagemagick/magick-wasm` gets build using Webpack before uploading to NPM, finding that solution should not be necessary. Which is probably preferable, as having to change a lot of configuration for your project just to use a library probably prevents a lot of people from using this. I'd like to hear your thoughts!

If you're interested in what I found to be the minimal build configuration, take a look below:
<details>
<summary>View code</summary>

Create a new npm project and run `npm i webpack webpack-cli ts-loader typescript @imagemagick/magick-wasm`. Then create the following files:
```js
// webpack.config.js
module.exports = {
  entry: "./main.ts",
  resolve: {
    fallback: {
      ws: false,
      fs: false,
      child_process: false,
      crypto: false,
      path: false,
    },
  },
  module: {
    rules: [{ test: /\.ts$/, loader: "ts-loader" }],
  },
  output: {
    filename: "main.js",
    library: { type: "module" },
  },
  experiments: { outputModule: true },
};
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "dist",
    "declaration": true,
    "module": "esnext",
    "moduleResolution": "node"
  },
  "files": ["./main.ts"]
}
```
```ts
// main.ts
export { ImageMagick, initializeImageMagick } from "@imagemagick/magick-wasm";
export * from "@imagemagick/magick-wasm/alpha-option";
export * from "@imagemagick/magick-wasm/auto-threshold-method";
export * from "@imagemagick/magick-wasm/channels";
export * from "@imagemagick/magick-wasm/color-space";
export * from "@imagemagick/magick-wasm/composite-operator";
export * from "@imagemagick/magick-wasm/distort-method";
export * from "@imagemagick/magick-wasm/drawables/drawable-color";
export * from "@imagemagick/magick-wasm/drawables/drawable-fill-color";
export * from "@imagemagick/magick-wasm/drawables/drawable-fill-opacity";
export * from "@imagemagick/magick-wasm/drawables/drawable-font";
export * from "@imagemagick/magick-wasm/drawables/drawable-font-point-size";
export * from "@imagemagick/magick-wasm/drawables/drawable-text";
export * from "@imagemagick/magick-wasm/error-metric";
export * from "@imagemagick/magick-wasm/evaluate-operator";
export * from "@imagemagick/magick-wasm/filter-type";
export * from "@imagemagick/magick-wasm/gravity";
export * from "@imagemagick/magick-wasm/image-magick";
export * from "@imagemagick/magick-wasm/magick-color";
export * from "@imagemagick/magick-wasm/magick-colors";
export * from "@imagemagick/magick-wasm/magick-error-severity";
export * from "@imagemagick/magick-wasm/magick-error";
export * from "@imagemagick/magick-wasm/magick-format-info";
export * from "@imagemagick/magick-wasm/magick-format";
export * from "@imagemagick/magick-wasm/magick-geometry";
export * from "@imagemagick/magick-wasm/magick-image-collection";
export * from "@imagemagick/magick-wasm/magick";
export * from "@imagemagick/magick-wasm/orientation-type";
export * from "@imagemagick/magick-wasm/paint-method";
export * from "@imagemagick/magick-wasm/percentage";
export * from "@imagemagick/magick-wasm/pixel-channel";
export * from "@imagemagick/magick-wasm/pixel-interpolate-method";
export * from "@imagemagick/magick-wasm/point";
export * from "@imagemagick/magick-wasm/quantum";
export * from "@imagemagick/magick-wasm/virtual-pixel-method";
```
Then run `npx webpack` and you should get a `dist` folder containing `main.js` and `main.d.ts`.
</details>

**Comment by Peeterush** [comment]
Finally got the same thing working in Vite! Under the hood it uses Rollup, so using `rollup-plugin-ignore` and the following config does the trick:
```js
// vite.config.js
import { builtinModules } from "module";
import { defineConfig } from "vite";
import ignore from "rollup-plugin-ignore";

export default defineConfig({
  build: {
    rollupOptions: {
      plugins: [ignore([...builtinModules, "ws"])],
      // or:
      // plugins: [ignore(["ws", "fs", "child_process", "crypto", "path"])],
    },
  },
});
```

**Comment by dlemstra** [comment]
Thanks for your help, can we close this issue?

**Comment by Peeterush** [comment]
We now know a workaround, but should the underlying issue not be resolved first? I can make a PR that adds a build step either based on Vite or on Webpack, if you'd like.

**Comment by dlemstra** [comment]
Can we close this now?

**Comment by Peeterush** [comment]
I'd wait till next release, when this is no longer necessary!

**Comment by Helehelehele** [comment]
When do you plan to publish the next release @dlemstra?

**Comment by dlemstra** [comment]
The new release has been publish but is broken. The `index.ts` file does not export everything. I wonder if this file should be generated.

**Comment by dlemstra** [comment]
I will update it myself. I was also wondering why you did `export { ImageMagick, initializeImageMagick } from './image-magick';` instead of `export *`?

**Comment by Peeterush** [comment]
I based the `index.ts` it on the one from the `wasm-builds` library you linked somewhere above, and they did it that way there. But as I pointed out in #55, I exported it both ways and fixed it there to just `export *`.

**Comment by dlemstra** [comment]
The new release has been publish @Peeterush and @Helehelehele. Can you give it another try and check if we can close this issue? And thank you for are your help to make this possible @Peeterush, and also for your other improvements.

**Comment by Peeterush** [comment]
My project now builds without any special configuration! Thank you for the great library.
