### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Vanilagy** [dlemstra/magick-wasm#43]
### magick-wasm version

0.0.10

### Description

Hey,

I'm using ImageMagick on my site for conversions and metadata extraction. But eventually, when the site runs long enough, I run into WASM running out of memory. I wanted to ask if this is a bug or oversight in this library, or if I'm incorrectly disposing of the resources I'm acquiring.

These are the two places I'm using it:

```ts
        /** Convert any image format (even niche stuff like BMP and DDS) to a PNG image buffer. */
	static nicheFormatToPng(nicheBuffer: Buffer) {
		return new Promise<Buffer>(resolve => {
			ImageMagick.read(nicheBuffer, image => {
				image.write(data => {
					resolve(Buffer.from(data));
					image.dispose();
				}, MagickFormat.Png);
			});
		});
	}

	static getImageDimensions(buffer: Buffer) {
		return new Promise<{ width: number, height: number }>(resolve => {
			ImageMagick.read(buffer, image => {
				resolve({
					width: image.width,
					height: image.height
				});
				image.dispose();
			});
		});
	}
}
```

I'm not calling ImageMagick anywhere else, and I also don't think I'm calling `initializeImageMagick` because it worked without.

### Steps to Reproduce

Not sure. Use my code and run it many times?

This is my error:

```
12|marblel | RuntimeError: memory access out of bounds
12|marblel |     at wasm://wasm/033f22f6:wasm-function[228]:0x15837
12|marblel |     at wasm://wasm/033f22f6:wasm-function[282]:0x345e3
12|marblel |     at wasm://wasm/033f22f6:wasm-function[242]:0x163cf
12|marblel |     at wasm://wasm/033f22f6:wasm-function[10796]:0x84b315
12|marblel |     at /site/marbleland/node_modules/@imagemagick/magick-wasm/magick-image.js:697:52
12|marblel |     at /site/marbleland/node_modules/@imagemagick/magick-wasm/internal/exception/exception.js:21:28
12|marblel |     at Function.use (/site/marbleland/node_modules/@imagemagick/magick-wasm/internal/pointer/pointer.js:15:20)
12|marblel |     at Function.usePointer (/site/marbleland/node_modules/@imagemagick/magick-wasm/internal/exception/exception.js:20:34)
12|marblel |     at Function.createInstance (/site/marbleland/node_modules/@imagemagick/magick-wasm/magick-image.js:696:38)
12|marblel |     at Function.create (/site/marbleland/node_modules/@imagemagick/magick-wasm/magick-image.js:292:44)
```

**Comment by dlemstra** [comment]
That looks like a different issue than running out of memory. I would also advise you to not dispose the image in this situation. Can you reproduce the issue if you remove the call to dispose?

**Comment by Vanilagy** [comment]
Alright, I was able to reproduce it. Looks like a memory leak to me.

```js
import { initializeImageMagick, ImageMagick } from '@imagemagick/magick-wasm';
import fs from 'fs';

let file = fs.readFileSync('path/to/image');
let count = 0;

while (true) {
	ImageMagick.read(file , image => {
		image.write(data => {
			image.dispose();
		}, 'PNG');
	});

	console.log(count++);
}
```

Make sure the image at the path exists. do this, and monitor the node memory going up slowly but steadily. After running this for 10 minutes, it died.

**Comment by dlemstra** [comment]
The `data` arrow is allocated but never freed. This should be done by magick-wasm after you return from the write method. I will push a patch for this tomorrow and try to publish a new release this weekend. Thanks for reporting this issue.

**Comment by Vanilagy** [comment]
Thanks for the fix! I'll be happy to use the updated version with peace of mind now.
