### ISSUE TITLE
Can't use the -brightness-contrast filter command.

### ISSUE THREAD

**Issue by shuvradeb-saha** [dlemstra/magick-wasm#50]
### Is your feature request related to a problem? Please describe.

Imagemagick has different commands to control the contrast of the images. This library already contains some of them. But most of them are legacy commands to control the brightness and/or contrast. We need the new brightness-contrast filter to control the contrast filter on the images.

### Describe the solution you'd like

I have added a new commit that contains the implementation of the brightness-contrast command. Here, is the [PR link](https://github.com/dlemstra/magick-wasm/pull/49) to my changes. Please check this commit out this is an important feature to us. It would be great if we get this in the next release.

**Comment by dlemstra** [comment]
Thanks for opening the pull request. You don't need to open up an issue first before creating a pull request so feel free to just create a pull request in the future.

I can publish a new release later this week if that would help you.

**Comment by shuvradeb-saha** [comment]
Thanks. That would be great! :+1:

**Comment by dlemstra** [comment]
The release has been published.

**Comment by shuvradeb-saha** [comment]
That's great! Thanks a lot.

**Comment by dlemstra** [comment]
Thank you for your contribution.
