### ISSUE TITLE
Output from local image magick command and magick-wasm is not the same.

### ISSUE THREAD

**Issue by shuvradeb-saha** [dlemstra/magick-wasm#52]
### magick-wasm version

0.0.15

### Description

I have been using this outstanding library with react-js for creating a basic image editor. It seems like sometimes the image output from the magick-wasm is not as similar as that I get from the command line tool of ImageMagick. I am using the following ImageMagick CLI on my local machine:-
```
Version: ImageMagick 7.1.0-48 Q16-HDRI x86_64 20449 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): jbig jng jpeg lzma png tiff zlib
Compiler: gcc (9.4)
```
**In most cases, I can see some color burn from the command line edit, and the burned place is pink or white in the magick-wasm edit.** I am not sure about if I need to tune any specific parameter or add any settings for making magick-wasm work as the one in the command line which is very important for my use case. Any help would be appreciated.

### Steps to Reproduce

I have used the following command to edit that image from the command line:-

`convert sports.jpg -brightness-contrast 0x50 -modulate 125x125 edit-local.jpg`

And the Javascript code:
```JavaScript
    ImageMagick.read(uint8array, readSettings, image => {
          image.brightnessContrast(
            new Percentage(0),
            new Percentage(50)
          );

          image.modulate(
            new Percentage(125),
            new Percentage(125)
          );

          image.write(data => {
            const blob = new Blob([data], { type: 'image/jpeg' });
            resolve(window.URL.createObjectURL(blob));
          });

        });
```

### Images

Edited using the command line:

![edit-cli](https://user-images.githubusercontent.com/25417062/192963503-7563c765-0f4e-48e1-9b19-c6653790ef1f.png)

Edited using magick-wasm:

![edit-wasm](https://user-images.githubusercontent.com/25417062/192963532-49dac7d8-8fd7-4e56-ac46-bb44e685965b.png)

**Comment by dlemstra** [comment]
Your local version is Q16-HDRI and there is now only a single wasm version that is 8 bit. That probably explains the difference. Can you reproduce the issue when you use Q8 in both environments?

**Comment by shuvradeb-saha** [comment]
Yes. You are right. After using the Q8 in both environments the result is the same. Thanks a lot!
