### ISSUE TITLE
Is it possible to add support to read EPS 

### ISSUE THREAD

**Issue by fmercerat** [dlemstra/magick-wasm#65]
### Is your feature request related to a problem? Please describe.

I have problems when I try to read an eps file. I think it needs ghostscript.

I get this error:
`index.mjs:5578 Uncaught (in promise) Error: FailedToExecuteCommand 'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pamcmyk32' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -g194x194  '-sOutputFile=/tmp/magick-yRx3GAbK1rrvsS6xCr_pHrrIA2HEldCO%d' '-f/tmp/magick-z3uabL56AdNvTxFcIoj1jg1fE1hIMmdK' '-f/tmp/magick-R4mfun_xe-r9BWfTFIjfbsG77JgcBooJ'' (-1) @ error/delegate.c/ExternalDelegateCommand/519
    at q.createError (index.mjs:5578:36)
    at q.throw (index.mjs:5574:17)
    at q.checkException (index.mjs:5562:35)
    at index.mjs:5555:16
    at ZA.use (index.mjs:5529:14)
    at q.use (index.mjs:5553:15)
    at JA.readOrPing (index.mjs:6881:7)
    at JA.read (index.mjs:6685:10)
    at index.mjs:6952:20
    at JA._use (index.mjs:6861:14)`

### Describe the solution you'd like

Is it posible to load a gs wasm?

**Comment by dlemstra** [comment]
I already gave an answer here: #51. Yes it might be possible but I can't add support for it due to licensing issues.
