### ISSUE TITLE
Can't tree shaking in Vite

### ISSUE THREAD

**Issue by TheXiong** [dlemstra/magick-wasm#75]
### magick-wasm version

0.0.19

### Description

![image](https://user-images.githubusercontent.com/43661809/223375081-d3dddd36-9638-43dc-9ebe-3aed72ee8e5e.png)
when I comment this code, tree shaking can works.

### Steps to Reproduce

1、create a vite(vue2) project
2、npm install
3、add below code
import { Gravity } from "@imagemagick/magick-wasm"
console.log(Gravity);
4、npm run build
5、view the bundle size
19772.80 KiB / gzip: 6829.42 KiB

**Comment by TheXiong** [comment]
@dlemstra how can I reduce the bundle size?

**Comment by dlemstra** [comment]
I don't think you can. The native library that uses ImageMagick has a lot of features and that increases the size of the bundle and I don't think you can tree shake that wasm code.

**Comment by TheXiong** [comment]
@dlemstra or can I split the code to serval files.

**Comment by dlemstra** [comment]
The orginal wasm size is around 19mb at this point in time. The source code is already split in multiple files but I think the bundler combines it.

**Comment by TheXiong** [comment]
@dlemstra why the size of _WASM-ImageMagick_ is just around 6mb?

**Comment by dlemstra** [comment]
I suspect that has to do with this library supporting the following delegates: `freetype heic jng jp2 jpeg jxl lcms lqr openexr png raw tiff webp xml zlib` and that library only supporting a subset of those delegates.

**Comment by TheXiong** [comment]
@dlemstra may I build a tiny wasm by myself?

**Comment by dlemstra** [comment]
You could reduce the binary size by removing some dependencies. But that will require you to modify the Magick.Native build and also make a custom build of magick-wasm.

**Comment by TheXiong** [comment]
@dlemstra I tried to exec build.cmd at https://github.com/dlemstra/Magick.Native/tree/main/build/wasm-x86, it generate a docker image, and then I dont known how to go on.

**Comment by dlemstra** [comment]
You can find the wasm files in the output directory.

**Comment by TheXiong** [comment]
@dlemstra but my output directory is empty, the output directory  is at https://github.com/dlemstra/Magick.Native/tree/main/build/wasm-x86/output? or in docker?

**Comment by TheXiong** [comment]
@dlemstra or I did some thing wrong when build?

**Comment by dlemstra** [comment]
I don't know what you have done but the output should be created in that folder. There might be something broken in your build but I cannot assist you with that. Going to close this issue now.

**Comment by TheXiong** [comment]
> t

ok, thank you.
