### ISSUE TITLE
Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/598

### ISSUE THREAD

**Issue by kechkibet** [dlemstra/magick-wasm#77]
### magick-wasm version

0.0.19

### Description

```
import { ImageMagick, MagickFormat } from "@imagemagick/magick-wasm";

function processImage(data) {
  ImageMagick.read(data, (image) => {
    image.write((rotData) => {
      // Process the image data
    }, MagickFormat.Tiff);
  });
}
```

// Call processImage multiple times
processImage(imageData);
processImage(imageData);

### Steps to Reproduce

data is in jpeg format
Call the processImage function with valid image data.
Call the processImage function again with the same image data.
The error occurs during the second call.

**Comment by dlemstra** [comment]
That is indeed what you should do. The `rotData` is only allocated during the execution of that delegate inside the write method.
