### ISSUE TITLE
Avif write error

### ISSUE THREAD

**Issue by shubhendusaurabh** [dlemstra/magick-wasm#78]
### magick-wasm version

0.0.19

### Description

magick-wasm throws error when writing to `avif` format.
 
`Error: Encoder plugin generated an error: Unspecified: Failed to encode frame (8.0) /tmp/magick-Nb-b1-7Fk2cC_fSgRnnFZ8vGkUHAjfKB' @ error/heic.c/IsHEIFSuccess/139`

### Steps to Reproduce

sample code=> https://codesandbox.io/s/blissful-joliot-u2zwx6?file=/src/index.js

```js
  file.arrayBuffer().then((d) => {
    initializeImageMagick()
      .then(async () => {
        ImageMagick.read(new Uint8Array(d), (image) => {
          image.write((data) => {
            const blob = new Blob([data], { type: `image/avif` });
            saveAs(blob, "avifimage.avif");
          }, MagickFormat.Avif);
        });
      })
      .catch((err) => {
        console.error("err", err);
      });
  });
```

**Comment by dlemstra** [comment]
I am in the middle of preparing a new release that will probably be published tomorrow. I can reproduce your issue on the master but I am getting this error message instead:

```
[Error]: Encoder plugin generated an error: Encoding problem: Tile encoder thread creation failed (8.5002) 
  `/tmp/magick-uLzqivPxr3RQKs9Evd7XTL2TU3GOgpnh' @ error/heic.c/IsHEIFSuccess/139
```

It seems there is an issue with creating a thread and that is expected of course but I don't know why this is happening. I will investigate this after the release.

**Comment by dlemstra** [comment]
It took me a while but I figured out what was causing this. The aom library was build incorrectly and had threads enabled while it should be disabled. This issue has been fixed in the Magick.Native repository and will be resolved in the next release. I also added a unit test to make sure this stays fixed.
