### ISSUE TITLE
.nef file type

### ISSUE THREAD

**Issue by akashilangovan** [dlemstra/magick-wasm#86]
### magick-wasm version

ImageMagick 7.1.1-8 Q8 x86_64 920f79206:20230422 

### Description

I am trying to convert .nef files to .jpg files by reading in a .nef file into an ImageMagick object and writing into a .jpg but the quality of the .jpg is much reduced(expecting 3MB but output is 30KB). Not sure if this is a known issue 

### Steps to Reproduce

file is an uploaded .nef image:
```
  const arrayBuffer = await file.arrayBuffer(); 
  const array1 = new Uint8Array(arrayBuffer);
  try {
    ImageMagick.read(array1, (image) => {
      image.write(MagickFormat.Png, (data) => {
        console.log(data);
      });
    });
  } catch (exception) {
    console.log(exception);
  }
```
the size of the output array is only 30kb as opposed to the expected 3mb. Image resolution is greatly reduced. 

### Images

Sample .nef file
[baby.nef.zip](https://github.com/dlemstra/magick-wasm/files/11471684/baby.nef.zip)

more can be found here:http://www.luminescentphoto.com/nx2/nefs.html

**Comment by dlemstra** [comment]
ImageMagick tries to autodetect the format from the buffer and finds a `tiff` header. This is happening because the `nef` file also contains a thumbnail that is stored as a tiff. To make sure you read this is a `nef` file you will need to do this:

```js
ImageMagick.read(array1, MagickFormat.Nef, (image) => {
```

**Comment by akashilangovan** [comment]
Ah, thank you that seems to have worked! Also, in terms of performance is it expected to take around 5 seconds to convert ~30mb file, or am I doing something wrong?

**Comment by dlemstra** [comment]
The nef image is not small (`4284x2844`) and decoding of these kind of files already takes a while so that is indeed what you should expect.
