### ISSUE TITLE
initializeImageMagick using UInt8Array of WASM Module

### ISSUE THREAD

**Issue by theomarkkuspaul** [dlemstra/magick-wasm#87]
### magick-wasm version

0.0.21

### Description

**This example is for the browser environment**

Curious how to initialize the ImageMagick WASM module by `fetch`-ing the `magick.wasm` file, then converting that into an `UInt8Array`, before passing that data into the `initializeImageMagick` function.

It would appear the initialization function supports the `magick.wasm` file as an 8-bit array as defined [here](https://github.com/dlemstra/magick-wasm/blob/4d3e8f4eeb927ca76f8e07db7f32d5d00df0edce/src/image-magick.ts#L68), but running this in the browser doesn't appear to be working for me.

Here's a rudimentary example of what I mean:

```js
import {
    initializeImageMagick,
} from "@imagemagick/magick-wasm";

(async () => {
    const wasmLocation = new URL('http://localhost:7000/magick.wasm').href;  // basic web server using the `http-server` npm package
    const wasmResponse = await fetch(wasmLocation);
    const wasmBuffer = await wasmResponse.arrayBuffer();
    const wasmBytes = new Uint8Array(wasmBuffer);

    await initializeImageMagick(wasmBytes);
})();
```

Console gives me this error `Uncaught (in promise) TypeError: t.startsWith is not a function`.

Bundling using `esbuild`, not sure that's doing anything strange or not.

For what it's worth, passing a URL as the wasm location into `initializeImageMagick` imports the wasm module fine.

AKA
```js
(async () => {
    const wasmLocation = new URL('http://localhost:7000/magick.wasm').href;
    await initializeImageMagick(wasmLocation);
})();
```

Thanks!

### Steps to Reproduce

Example in bug description.

### Images

![magick-wasm bad import](https://github.com/dlemstra/magick-wasm/assets/13745712/a2473bba-de0b-4409-ae4a-95b70e0b8fc2)

**Comment by dlemstra** [comment]
That functionality has not yet been released. This will become available in the next release. If you really need this I can publish a new release sooner?

**Comment by theomarkkuspaul** [comment]
No rush, thanks for the update!
