### ISSUE TITLE
Error: instance is disposed when I trying to wrap ImageMagick.read() into a async function.

### ISSUE THREAD

**Issue by 321638914** [dlemstra/magick-wasm#93]
### magick-wasm version

0.0.21

### Description

Got instance is disposed error when I trying to wrap ImageMagick.read into a async function.
![image](https://github.com/dlemstra/magick-wasm/assets/85913672/7f0acc6b-116b-46f2-82d8-7d66976cad97)

### Steps to Reproduce

Here is a minimal reproduce project:
https://stackblitz.com/edit/vitejs-vite-cce4od?file=src%2Fim.ts

**Comment by dlemstra** [comment]
You cannot resolve/return the image that was created inside the read method. This image uses "native" memory inside the wasm code that should be freed. You could however load the image differently but then it will become your responsibility to dispose the image:

```js
const i: IMagickImage = await new Promise((resolve, reject) => {
    const image = MagickImage.create();
    image.read(new Uint8Array(arrbuff));
    resolve(image);
});

i.dispose();
```

**Comment by 321638914** [comment]
Thanks for help! Maybe add a notice in document or demo?
